version: "2.1"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - ./multimedia-project/jacket/config:/config
      - ./multimedia-project/jacket/downloads/:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - ./multimedia-project/transmission/config:/config
      - ./multimedia-project/transmission/downloads:/downloads
      - ./multimedia-project/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./multimedia-project/sonarr/config:/config
      - ./multimedia-project/jellyfin/tv-series:/tv
      - ./multimedia-project/transmission/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./multimedia-project/radarr/config:/config
      - ./multimedia-project/jellyfin/movies:/movies
      - ./multimedia-project/transmission/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./multimedia-project/jellyfin/config:/config
      - ./multimedia-project/jellyfin/tv-series:/data/tvshows
      - ./multimedia-project/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./multimedia-project/bazarr/config:/config
      - ./multimedia-project/jellyfin/movies:/movies
      - ./multimedia-project/jellyfin/tv-series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./multimedia-project/nzbhydra2/config:/config
      - ./multimedia-project/nzbhydra2/downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped

  organizr:
    image: linuxserver/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./multimedia-project/organizr/config:/config
    ports:
      - 9983:80
    restart: unless-stopped

  heimdall :
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./multimedia-project/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped